# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170106_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='identifier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='target_ID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
