# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170106_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(default='', upload_to='apps/icons/'),
            preserve_default=False,
        ),
    ]
