# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='BOLOS_app_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='bolos_max_firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_version', to='api.Firmware'),
        ),
        migrations.AddField(
            model_name='version',
            name='bolos_min_firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='min_version', to='api.Firmware'),
        ),
        migrations.AddField(
            model_name='version',
            name='firmware',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='firmware_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='perso',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
