# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170106_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='firmware',
            name='pre_release_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firmware',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='pre_release_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
