# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170106_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='final_firmware',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='final_firmware_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='final_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.RegexValidator(code='invalid_hash', message='Hash must be an hexadecimal value', regex='^[a-fA-F0-9]*$')]),
        ),
        migrations.AddField(
            model_name='firmware',
            name='final_perso',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='osu_firmware',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='osu_firmware_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='osu_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.RegexValidator(code='invalid_hash', message='Hash must be an hexadecimal value', regex='^[a-fA-F0-9]*$')]),
        ),
        migrations.AddField(
            model_name='firmware',
            name='osu_perso',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='app_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.RegexValidator(code='invalid_hash', message='Hash must be an hexadecimal value', regex='^[a-fA-F0-9]*$')]),
        ),
    ]
