# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170106_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='app',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='app',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='target_ID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
